### ISSUE TITLE
Criação do repositório do projeto

### ISSUE THREAD

**Issue by edmarrn** [Asset-Sentry/principal#1]
## De acordo com as decisões e tarefas definidas tomadas na reunião segue abaixo as tarefas distribuídas:
**1-Criação de repositório para o projeto**
         Descrição: Criação de uma conta de organização na plataforma Github. Inclusão do email dos alunos e dos orientadores.
**2- Criação do arquivo readme no repositório**
        Descrição: Submissão da proposta do projeto corrigida no arquivo readme do repositório.
**3-Inclusão** do planejamento dos seis sprints como milestones
        Descrição: criação e configuração de seis marcos (milestones) no GitHub para representar as entregas do projeto.
**4-Planejamento do primeiro sprint em termos de issues**
        Descrição: criação de no mínimo um issue por membro de grupo em cada sprint/milestone.
**5-Elaboração do relatório da atividade**
        Descrição: Elaboração de relatório com os resultados obtidos no repositório do projeto, incluindo todas as 
        atividades que foram desenvolvidas por cada membro do grupo.
**6-Revisão e submissão do relatório**
        Descrição: Revisão do relatório elaborado verificando se está em conformidade com o solicitado na atividade. 
        Após revisão, submeter no classroom.

![image](https://github.com/user-attachments/assets/946f23fe-970e-4dcf-8385-ba9a60cfce9d)

**Comment by edmarrn** [comment]
No primeiro sprint, nos reunimos para definir a plataforma de pesquisa e desenvolvimento do projeto. Discutimos e decidimos sobre as seguintes características:
Banco de dados a ser utilizado, plataforma de dashboard para a interação como o monitoramento e coleta de dados, instalação e configuração dos sensores compatíveis com Arduíno, construção do código e a configuração e interação do asterisk para chamadas e alerta via Voip.

**Comment by wesleycstr** [comment]
Repositório Criado no dia 27/07/2024; e
Já iniciei a confecção do relatório.

**Comment by wesleycstr** [comment]
Para criação de repositório para o projeto, utilizou-se a plataforma Github. Escolheu-se criar uma conta de organização devido a mesma atuar como um contêiner para o trabalho compartilhado. Também chamou a nossa atenção a possibilidade de atrelarmos o contêiner a nossa marca, deixando-o mais personalizado. Inseri a logomarca do nosso projeto e enviei os convites para os professores.

**Comment by edmarrn** [comment]
No Sprint 01 na qual eu fiquei responsável do Levantamento de serviços e métodos necessários para coleta, envio, armazenagem, tratamento e automatização de alertas, em anexo segue a documentação do que eu pesquisei e também estará inserido no relatório nesta entrega.
[Planejamento dos sprints.pdf](https://github.com/user-attachments/files/16436353/Planejamento.dos.sprints.pdf)
