### ISSUE TITLE
Sprint 03 (Matheus): Pesquisa de ferramentas de criação de gráficos / integração com banco de dados

### ISSUE THREAD

**Issue by wesleycstr** [Asset-Sentry/principal#10]
Pesquisar maneiras de inserir gráficos para nossa página e integrar com o banco de dados de maneira que se carregue com os dados armazenados.

**Comment by wesleycstr** [comment]
### Sprint 03 (Matheus): Pesquisa de ferramentas de criação de gráficos / integração com banco de dados
Matheus, uma boa ferramenta é a charts.js que possue gráficos em javascript. São grátis e são moldáveis de acordo com as nossas necessidades. Assim como o chart.js, existe o gaug.js que são ferramentas para exibir os dados em formato de medidores. Acredito que dá para usar no nosso projeto!

**Comment by britox-x** [comment]
Sugestão de usar o Chart.js e o Gauge.js no nosso projeto é ótima. O Chart.js se destaca como uma biblioteca versátil em JavaScript, ideal para criar gráficos interativos e adaptáveis às nossas necessidades. Ele oferece uma variedade de gráficos, como linhas, barras, pizza e radar, e é altamente customizável, permitindo que ajustemos os gráficos de acordo com as demandas do projeto. Além disso, a integração com fontes de dados é simples, e os gráficos são responsivos, garantindo acessibilidade em diferentes dispositivos.

O Gauge.js complementa bem o Chart.js, focando na criação de medidores, perfeitos para visualizar indicadores como uso de CPU ou temperatura dos servidores. Sua implementação é simples e leve, com opções de personalização que permitem integrar os medidores ao design do nosso dashboard. As animações suaves do Gauge.js também são um diferencial, melhorando a visualização dos dados em tempo real.

![image](https://github.com/user-attachments/assets/39f49d46-a270-462a-b1de-a9bfa2ccc149)

![image](https://github.com/user-attachments/assets/6c6d9682-2522-4f93-9ce5-baa0f8d7f26b)

**Comment by wesleycstr** [comment]
**Link para a página com código para Line Chart**

![image](https://github.com/user-attachments/assets/503d8126-2cc8-4f92-bd5a-ba2ab262d94d)


https://www.chartjs.org/docs/latest/samples/line/line.html

**Comment by wesleycstr** [comment]
**Link para a página com código para mostradores**
![image](https://github.com/user-attachments/assets/cb37769b-4592-46b9-938a-228ad28b6fb7)

https://plotly.com/javascript/gauge-charts/

**Comment by wesleycstr** [comment]
O resultado final da interface gráfica:
![image](https://github.com/user-attachments/assets/5d5d0e7c-6b4c-47d8-880f-1d0b8885bc96)
