### ISSUE TITLE
Sprint 04 (Edmar): Criação de fluxograma para as consultas e alertas automatizados via VOIP.

### ISSUE THREAD

**Issue by wesleycstr** [Asset-Sentry/principal#13]
# Criação de fluxograma para as consultas e alertas automatizados via VOIP.
### Chamada para o ramal *101 => Ramal atende ligação => Sistema informa a temperatura, umidade e nível de CO2 => Sistema encerra a chamada.

**Comment by wesleycstr** [comment]
## Dinâmica para chamadas de consulta (Ramal 101):

### Usuário disca 101 => Central atende a ligação => Central informa os dados obtidos do banco de dados (1) => Central repete os valores até que o usuário encerre a chamada.

#### (1) Sugestão para frase a ser dita pela central: "Olá! Neste momento a temperatura da sala de servidores está em ... graus célsius. A umidade está em ... porcento e o nível de CO2 está em ... partes por milhão"

**Comment by edmarrn** [comment]
O detalhamento do fluxograma é muito importante para um  nó de decisão, principalmente se houver um falha da consulta dos dados, como por exemplo: sensor disponível.

**Comment by edmarrn** [comment]
De acordo com o que foi comentado estou enviando uma imagem do fluxograma, uma idealização.

![image](https://github.com/user-attachments/assets/0563ef80-fdfe-4b2a-b086-ee94dc46e153)

**Comment by edmarrn** [comment]
Aqui temos uma descrição passo a passo do fluxograma.
Descrição do Fluxograma:

    Chamada Recebida: O ramal 101 recebe uma chamada.
    Atendimento Automático: A chamada é atendida automaticamente pelo sistema VOIP.
    Coleta de Dados: O sistema consulta a fonte de dados para obter os valores de temperatura, umidade e CO2.
    Geração da Mensagem: O sistema gera uma mensagem de voz utilizando TTS, informando os valores coletados. Por exemplo: "A temperatura atual é de 22 graus Celsius, a umidade é de 50% e o nível de CO2 é de 400 ppm."
    Reprodução da Mensagem: A mensagem gerada é reproduzida para o usuário.
    Encerramento da Chamada: A chamada é encerrada automaticamente após a reprodução da mensagem.

**Comment by wesleycstr** [comment]
Obrigado Edmar!<br>
![image](https://github.com/user-attachments/assets/f8314316-705c-433e-a9bf-9f4f3e60c74c)<br><br>
![image](https://github.com/user-attachments/assets/c4e75618-e4e1-4028-9c66-1ea0c4fd08d4)
