### ISSUE TITLE
Sprint 05 (Edmar): Análise de vulnerabilidades.

### ISSUE THREAD

**Issue by wesleycstr** [Asset-Sentry/principal#15]
## Analisar as possíveis vulnerabilidades do sistema.
Edmar, preciso que vc faça uma análise das possíveis falhas que possam acontecer e juntos vamos melhorar o projeto. O foco é evitar que de alguma forma o sistema deixe de exibir os dados ou não consiga enviar os alertas.

**Comment by edmarrn** [comment]
Tarefa 01: Análise de vulnerabilidades.
O propósito desta tarefa é analisar problemas que venham a ocorrer e que possam resultar em falhas. Tais vulnerabilidades devem ser mitigadas para que o processo de monitoramento que estamos propondo funcione minimamente com confiabilidade.
Desta forma, após análise das situações, discriminamos estes pontos como sendo os mais relevantes e as possíveis soluções para serem implementadas:
- A interface gráfica está acessível para qualquer usuário que acessar a rede
Consequência: Qualquer pessoa estando conectada na mesma rede poderá acessar a página da ferramenta digitando o endereço em um navegador. Pessoas com acesso indevido poderão alterar parâmetros e gerar alertas falsos.

**Comment by edmarrn** [comment]
Solução: Criar página de login para limitar uso dos recursos. com utilização de autenticação em 2 etapas e definir o nível de permissões de acordo com o tipo de usuários. Ter uma restrição de acesso por IP. ou seja um ACL, poderemos usar uma criptografia.

**Comment by wesleycstr** [comment]
> Solução: Criar página de login para limitar uso dos recursos. com utilização de autenticação em 2 etapas e definir o nível de permissões de acordo com o tipo de usuários. Ter uma restrição de acesso por IP. ou seja um ACL, poderemos usar uma criptografia.

Feito!<br>
![image](https://github.com/user-attachments/assets/b9ee967c-727e-4098-b58b-f20ca060c8f0)<brV

**Comment by edmarrn** [comment]
De acordo que foi pesquisado, foi observado que para o sistema continue funcionando corretamente, mesmo após uma queda da rede, pode se modificar o código hospedado na placa Wemos, para verificar se continuamente a conexão da rede. Se a conexão for perdida, o dispositivo deve se conectar automaticamente.

**Comment by edmarrn** [comment]
Aí, podemos criar uma estratégia para a reconexão automática, que são a verificação continua de conexão, rotina de reconexão, configuração de timeout, logs e feedbacks.

**Comment by edmarrn** [comment]
Alguns pontos que podemos melhorar são: 
Vulnerabilidade o código tentar se conectar apenas 1 vez, na inicialização, se a conexão wi-fi for perdida depois disso, o dispositivo não fará uma nova tentativa, 
Solução sugerida é uma criação de loop para verificar se o dispositivo ainda está conectado ao wi-fi:

**Comment by edmarrn** [comment]
Aqui temos a imagem do código que pode ser melhorado.

![image](https://github.com/user-attachments/assets/9086ad9d-8d92-4800-b446-351a0eda9a38)

![image](https://github.com/user-attachments/assets/6071006e-bdf5-4daa-95df-d6ac4a0ea211)


![image](https://github.com/user-attachments/assets/1a2865a3-c863-4499-9e3b-ee478023db21)

**Comment by edmarrn** [comment]
Para garantir que os operadores e administradores possam acompanhar o funcionamento do sistema e identificar rapidamente qualquer problema, é essencial implementar um sistema de registro de logs eficiente.

**Comment by edmarrn** [comment]
Solução: Criar tabela no banco de dados que seja alimentada com informações de log a cada execução de script. Gerar uma visualização na página web para que os usuários possam acompanhar as mensagens que estão sendo geradas.

**Comment by edmarrn** [comment]
Não há confirmação do usuário de recebimento de alerta via telefone
Consequência: Quando não há confirmação de recebimento de alerta pelo usuário o sistema fica insistentemente gerando chamadas até mesmo nos casos que o destinatário recebeu a ligação.

**Comment by wesleycstr** [comment]
> Aqui temos a imagem do código que pode ser melhorado.
> 
> ![image](https://private-user-images.githubusercontent.com/46844536/363030976-9086ad9d-8d92-4800-b446-351a0eda9a38.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjUxMDYyNzgsIm5iZiI6MTcyNTEwNTk3OCwicGF0aCI6Ii80Njg0NDUzNi8zNjMwMzA5NzYtOTA4NmFkOWQtOGQ5Mi00ODAwLWI0NDYtMzUxYTBlZGE5YTM4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MzElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODMxVDEyMDYxOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTNjY2NiZGVjNTMxM2M2YmVkMjk2MGRkODM4YWI1M2MzOTc3NWFiYTU5MGY1NWFmMThlYzk1OGQ5NWZiMDMyMGUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.m_4TPvhNbLSmavHfdHEBJhoTt20UUfzvteGE-7ynnls)
> 
> ![image](https://private-user-images.githubusercontent.com/46844536/363031222-6071006e-bdf5-4daa-95df-d6ac4a0ea211.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjUxMDYyNzgsIm5iZiI6MTcyNTEwNTk3OCwicGF0aCI6Ii80Njg0NDUzNi8zNjMwMzEyMjItNjA3MTAwNmUtYmRmNS00ZGFhLTk1ZGYtZDZhYzRhMGVhMjExLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MzElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODMxVDEyMDYxOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU5M2YzMzBkNGEzY2IyOGJiZGJiZTFjODljMjkzOTQ2NjRjZjU3YTE2MjczMzkyOGRlNWNmMTAwNmJlMzZmNzkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.PLPwN5MIPqq386OnUg_Dq0KFIOHf-baKg4QhtQQN7t4)
> 
> ![image](https://private-user-images.githubusercontent.com/46844536/363031367-1a2865a3-c863-4499-9e3b-ee478023db21.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjUxMDYyNzgsIm5iZiI6MTcyNTEwNTk3OCwicGF0aCI6Ii80Njg0NDUzNi8zNjMwMzEzNjctMWEyODY1YTMtYzg2My00NDk5LTllM2ItZWU0NzgwMjNkYjIxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MzElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODMxVDEyMDYxOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTIzODdhMmNjN2FiOTgzMzg4YmI1YzY2OTFhNDkxM2RkYTcwZWQ4ZTVmYzk1M2IyNDhlODYzNjU4ODBjOGE1MjImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.YlbueIyhSF4MrxKa0Ac-TTJ1REiUgGWYiCookLPV0Lg)

Adicionei dentro do loop uma verificação de conexão e reconexão caso necessário.<br>
![image](https://github.com/user-attachments/assets/9fc3c1d5-6976-476f-8a71-4378d8f20a40)

**Comment by wesleycstr** [comment]
> Solução: Criar tabela no banco de dados que seja alimentada com informações de log a cada execução de script. Gerar uma visualização na página web para que os usuários possam acompanhar as mensagens que estão sendo geradas.

## Criado um script que armazena os dados de logs
![image](https://github.com/user-attachments/assets/f51a5653-6155-40e0-96c0-5936f245ab9e)
## Criada uma página para visualização:
![image](https://github.com/user-attachments/assets/2d3e1c40-28e3-4f53-a1e0-76fafa9a8e4d)

**Comment by edmarrn** [comment]
As atualizações foram medidas bem assertivas, essas atualizações deixará o sistema mais seguro.

**Comment by wesleycstr** [comment]
Obrigado Edmar! Issue fechada.
