### ISSUE TITLE
Sprint 05 (Matheus): Testes de segurança.

### ISSUE THREAD

**Issue by wesleycstr** [Asset-Sentry/principal#17]
## Efetuar os testes reproduzindo diferentes situações em que nosso projeto poderá ser empregado.
Matheus, você será responsável em testar a nossa tecnologia. Veja com o Professor Ivanilson a possibilidade de testar no IF ou mesmo em outro lugar. Vamos ver se conseguimos valuidar a temperatura e o nível de CO2 através de aparelhos de teste.

**Comment by britox-x** [comment]
Os testes focam em como o ambiente se comunicará com os sensores AHT10, DHT22 e MQ-135. Primeiro, vou destacar o que cada sensor catalogará para fornecer os avisos de monitoramento:

AHT10: responsável pela medição de temperatura e umidade, fornecendo dados precisos que serão usados para alertas de condições ambientais fora dos limites estabelecidos.
DHT22: outro sensor de temperatura e umidade, mas com maior faixa de operação e precisão, oferecendo uma redundância e validação cruzada dos dados ambientais.
MQ-135: sensor de gases, usado para monitorar a qualidade do ar, especialmente detectando níveis de CO2 e outros gases nocivos que são críticos para o ambiente monitorado.
Esses sensores fornecerão os dados essenciais que, ao serem analisados pelo sistema, desencadearão os avisos de monitoramento necessários.

**Comment by britox-x** [comment]
Realizando os testes, estamos queimando papel em um recipiente e utilizando um soprador térmico para detectar a fumaça e o calor. Esse processo ajuda a validar os sensores de monitoramento de fumaça e temperatura no projeto Asset Sentry, assegurando que as notificações e alertas funcionem corretamente diante de condições críticas.

**Comment by britox-x** [comment]
Além disso, estamos utilizando um método de resfriamento após o aquecimento e, em seguida, deixando o sistema retornar à temperatura ambiente. Esse ciclo de aquecimento e resfriamento é essencial para avaliar a resposta dos sensores em diferentes condições térmicas, garantindo que o Asset Sentry possa detectar mudanças rápidas e retornar a estados normais com precisão.

**Comment by britox-x** [comment]
Pretendemos realizar o teste em breve utilizando uma maquete feita com uma caixa de madeira que simula o sistema final. Nessa configuração, a caixa representará os servidores, enquanto os sensores estarão estrategicamente posicionados nas paredes internas. Isso nos permitirá avaliar como o Asset Sentry se comporta em um ambiente mais realista, testando a eficiência dos sensores na detecção de anomalias de temperatura e fumaça, simulando um data center em escala reduzida.

**Comment by wesleycstr** [comment]
> Realizando os testes, estamos queimando papel em um recipiente e utilizando um soprador térmico para detectar a fumaça e o calor. Esse processo ajuda a validar os sensores de monitoramento de fumaça e temperatura no projeto Asset Sentry, assegurando que as notificações e alertas funcionem corretamente diante de condições críticas.

Olha aí Matheus, deu certo!<br>
# Teste com detector de fumaça:<br>
![image](https://github.com/user-attachments/assets/94bd67c2-c53e-4af3-b440-979e6418daef)<br>
![image](https://github.com/user-attachments/assets/124aad12-7489-4e3f-9f2e-79bdb38abcc2)<br>
![image](https://github.com/user-attachments/assets/545890bf-6256-4cbb-a2e2-cbadec2ff1e0)<br>
![image](https://github.com/user-attachments/assets/c39c3f56-b62c-478e-b8c0-6549b5c48c5f)<br>
![image](https://github.com/user-attachments/assets/d0f69d96-a7d3-48f7-8528-3044606fdae8)<br>
![image](https://github.com/user-attachments/assets/7d18e831-d227-4811-9da3-1f6170662599)<br>
![image](https://github.com/user-attachments/assets/f687e658-b6ef-4a09-9042-309462afe514)<br>
# Teste com detector de temperatura:<br>
![image](https://github.com/user-attachments/assets/89c4dfc7-0d7e-48b7-8b45-ecf389eb2602)<br>
![image](https://github.com/user-attachments/assets/de100a0f-59aa-4470-8570-b340629d7d64)<br>
![image](https://github.com/user-attachments/assets/7f05f8de-b530-44bc-8f06-434da23096c5)<br>
![image](https://github.com/user-attachments/assets/d6c88401-b192-4002-a54c-0fef9174abd7)<br>
![image](https://github.com/user-attachments/assets/eee75b09-dc14-44c0-afc5-b5a8b8941fa7)<br>
![image](https://github.com/user-attachments/assets/7ea28ab2-b8df-4a16-8421-cf0b6985959a)<br>

**Comment by wesleycstr** [comment]
> Pretendemos realizar o teste em breve utilizando uma maquete feita com uma caixa de madeira que simula o sistema final. Nessa configuração, a caixa representará os servidores, enquanto os sensores estarão estrategicamente posicionados nas paredes internas. Isso nos permitirá avaliar como o Asset Sentry se comporta em um ambiente mais realista, testando a eficiência dos sensores na detecção de anomalias de temperatura e fumaça, simulando um data center em escala reduzida.

## Continue a confecção da maquete, vai ser útil para a demonstração!

**Comment by wesleycstr** [comment]
Obrigado Matheus! Issue fechada.
