### ISSUE TITLE
Sprint 06 (Matheus): Criar manual de usuário.

### ISSUE THREAD

**Issue by wesleycstr** [Asset-Sentry/principal#18]
Criar um passo a passo para a utilização da ferramenta.

**Comment by britox-x** [comment]
Descrição:
Precisamos criar um manual de usuário completo que explique como usar o sistema, desde a integração com plataformas como Zabbix e Grafana, até a utilização da nossa interface gráfica. O objetivo é garantir que todos os usuários saibam como aproveitar ao máximo todas as funcionalidades do sistema.

**Comment by britox-x** [comment]
Issue 2: Integração com Zabbix
Descrição:
Documentar o processo de integração do sistema com a plataforma Zabbix usando o protocolo SNMP.

Passos a Seguir:

Criar Novo Host no Zabbix

O que fazer: Crie um novo host no Zabbix e adicione uma interface SNMP.
Referência: Veja como fazer isso na Figura 02.
Adicionar Itens ao Host

O que fazer: Configure itens para monitorar temperatura, umidade e nível de monóxido de carbono usando os OIDs abaixo:
Temperatura: iso.3.6.1.4.1.5.10
Umidade: iso.3.6.1.4.1.5.11
Nível de CO: iso.3.6.1.4.1.5.12
Referência: A Figura 03 mostra como configurar esses itens.
Configurar Dashboards

O que fazer: Adicione e configure dashboards para visualizar os dados dos sensores.
Referência: Exemplo na Figura 04.

**Comment by britox-x** [comment]
Usando a Interface Gráfica
Descrição:
Explicar como usar nossa interface gráfica para visualizar dados e configurar alertas.

Passos a Seguir:

Acesso e Página Inicial

O que fazer: Mostre como fazer login e descreva os principais elementos da página inicial.
Referência: Veja a Figura 05.
Configuração da Barra Lateral

O que fazer: Detalhe as funções disponíveis na barra lateral esquerda e como configurá-las.
Funções Principais:
Notificação por VoIP
Alerta sonoro
Alarme Local
Equipamento Reserva
Referência: Veja como é a barra lateral na Figura 06.
Visualização dos Valores com Gauges

O que fazer: Explique como acompanhar os valores em tempo real através dos gráficos gauges.
Referências:
Temperatura: Figura 07
Umidade: Figura 08
Nível de CO: Figura 09
Gráficos Line Chart

O que fazer: Mostre como visualizar dados históricos com gráficos line chart.
Referências:
Temperatura: Figura 10
Umidade: Figura 11
Nível de CO: Figura 12
Página de Logs

O que fazer: Explique como acessar e interpretar a página de logs para verificar mensagens do sistema.
Referência: Veja a Figura 13.

**Comment by britox-x** [comment]
Utilização do Protótipo
Descrição:
Fornecer detalhes sobre o protótipo, incluindo suas características técnicas e o comportamento do LED indicador. Isso ajudará os usuários a entender melhor o hardware e como interpretá-lo.

Passos a Seguir:

Características Técnicas do Protótipo

O que fazer: Descreva as características técnicas do protótipo, como dimensões, peso, e especificações dos sensores.
Referência: Veja a Tabela 04 para todos os detalhes técnicos.
Sensores e LED Indicador

O que fazer: Explique a localização dos sensores e o que significa cada comportamento do LED.
Referências:
Sensores e LED: Figura 14
Ímãs para Fixação: Figura 15
Tabela de Comportamento do LED:
Piscando continuamente: Tentando conectar ao Wi-Fi
Aceso por dois segundos: Perda do sinal Wi-Fi
Três piscadas seguidas: Conectado ao Wi-Fi, falha ao enviar dados
Aceso por um segundo com duas piscadas rápidas: Conectado e enviando dados

**Comment by wesleycstr** [comment]
Obrigado Matheus!
