### ISSUE TITLE
Sprint 06 (Edmar): Preparar um relatório técnico abrangente, documentando o processo de desenvolvimento.

### ISSUE THREAD

**Issue by wesleycstr** [Asset-Sentry/principal#19]
Relatório com todos os processos de desenvolvimento do projeto.

**Comment by edmarrn** [comment]
Iniciando o processo de produção do relatório técnico do projeto.

**Comment by edmarrn** [comment]
O relatório tem como objetivo de registrar as etapas de desenvolvimento e os resultados alcançados no projeto Asset Sentry. Ele contém informações sobre os requisitos do sistema, as tecnologias implementadas, as dificuldades encontradas e as soluções desenvolvidas, tendo como um recurso de consulta tanto para o grupo do projeto, quanto para os futuros interessados no nosso trabalho.

**Comment by edmarrn** [comment]
Os processos do desenvolvimento do projeto segui uma linha de produção, na qual de acordo com as necessidades fomos adaptando ferramentas para a otimização do dispositivo.

**Comment by edmarrn** [comment]
![Screenshot_20240908-191453](https://github.com/user-attachments/assets/8cc12040-a0fb-40a9-b868-699b56b7d850)

**Comment by edmarrn** [comment]
![Screenshot_20240909-001127](https://github.com/user-attachments/assets/89157766-8d7b-4ece-8ecf-47c84d11010a)

**Comment by edmarrn** [comment]
Acima temos a criação do host snmp na plataforma zabbix. Nesta plataforma a visualização do que está monitorado ficará mais abrangente.

**Comment by edmarrn** [comment]
Exemplo dos parâmetros de taxa de temperatura, gás e humildade do ar.
![image](https://github.com/user-attachments/assets/b27c87bb-a97d-48ae-bce7-10bb323dfe8f)

**Comment by edmarrn** [comment]
Após criação dos itens adicione os dashboards de acordo com as necessidades de visualização. A figura 04 demonstra um exemplo de dashboard criado para visualização dos dados dos sensores.
![image](https://github.com/user-attachments/assets/d77c28c0-495a-4c57-baa4-16c41fd7ac72)

**Comment by edmarrn** [comment]
Aqui temos a interface gráfica própria para o acompanhamento.
![image](https://github.com/user-attachments/assets/989afe18-77a6-469b-9f83-aeb51ad77467)

**Comment by wesleycstr** [comment]
Obrigado Edmar!
