### ISSUE TITLE
Criação de maquete para testes e demonstração

### ISSUE THREAD

**Issue by wesleycstr** [Asset-Sentry/principal#21]
## Conforme combinado vamos construir uma maquete para os testes e demonstração.
Minha sugestão de modelo:
Obs.: Essas medidas precisam ser multiplicadas por 10 para transformar em centímetros.
![image](https://github.com/user-attachments/assets/62046e90-a593-4997-b81b-282d12d135c3)

**Comment by edmarrn** [comment]
Durante a confecção da base da maquete houve alguns ajustes, na qual tivemos algumas dificuldades com a escala, mas o problema foi resolvido, como mostra a imagem abaixo e conseguimos obter os resultados esperado.
![image](https://github.com/user-attachments/assets/bff8fdab-82f8-42c5-a3f8-c6997fceed0e)

**Comment by wesleycstr** [comment]
@britox-x, consegue fazer um modelo tridimensional da nossa maquete?

**Comment by britox-x** [comment]
A primeira ideia passada para o Tinkercad com suas supostas dimensões:

![image](https://github.com/user-attachments/assets/ab461969-c9b2-4795-8924-eefbb3d90093)

![image](https://github.com/user-attachments/assets/aa05f60c-6d08-409c-926e-a341c1899eda)

![image](https://github.com/user-attachments/assets/bad575e6-5b62-4b67-ae41-c385e4dfb6d3)

**Comment by britox-x** [comment]
Quis atribuir à maquete também um início de onde ficarão os componentes da maquete.

Ajustei para uma maior dimensão, coloquei um modelo para simular racks de rede, além dos sensores de fumaça, umidade e temperatura. Com o nome do nosso projeto acima. 
![image](https://github.com/user-attachments/assets/dea1d24e-8468-4afb-853e-ef3741e74d19)

Abaixo segue o controlador que recebe os dados dos sensores.
![image](https://github.com/user-attachments/assets/a94e72ea-7e31-4e4a-99bf-6389fc5eae4e)

Na lateral, haverá uma espécie de alarme para notificar internamente se algo ocorrer fora dos parâmetros.

![image](https://github.com/user-attachments/assets/aac48969-e0d1-47a1-bb50-b10657f1e0a2)

**Comment by edmarrn** [comment]
O resultado da construção da maquete foi excelente, capturando todos os detalhes conforme planejado.!(https://github.com/user-attachments/assets/57e5d92d-59fe-4da3-804a-adb87cecdc54)

**Comment by edmarrn** [comment]
A instalação do Asset Sentry :

![image](https://github.com/user-attachments/assets/ace727dc-f3cd-471f-969f-27b62e567292)

**Comment by britox-x** [comment]
Pintando as chapas com spray antichama fosco:

![image](https://github.com/user-attachments/assets/9e55b770-c484-4098-830f-b516c01100c9)

![image](https://github.com/user-attachments/assets/fb4737b6-5366-45f5-942d-457f9930ee75)

![image](https://github.com/user-attachments/assets/f32e984b-66d8-4f52-9364-533d551e0f0e)

**Comment by britox-x** [comment]
Adicionando os componentes eletrônicos para realizar os testes.

Microcontrolador posicionado junto ao protoboard: 

![image](https://github.com/user-attachments/assets/c9f822db-624d-4dd8-b7ea-9872970cee06)

Cooler e sensores alocados:

![image](https://github.com/user-attachments/assets/d4520357-b11a-47fa-ad33-277e046fb6a4)

Relé com placa Wi-Fi e alarme de alerta.

![image](https://github.com/user-attachments/assets/a062f5b3-02ee-4af6-86bc-c9dd6d7a8eb2)

**Comment by edmarrn** [comment]
Abaixo está a imagem como está ficando a maquete,

![image](https://github.com/user-attachments/assets/12ead4a8-f9f3-4b43-ab1e-2057540dc877)
