### ISSUE TITLE
Sprint 01: Pesquisa de dispositivos, sensores e outros componentes necessários para captação e envio dos dados coletados

### ISSUE THREAD

**Issue by wesleycstr** [Asset-Sentry/principal#3]
# Objetivo deste Sprint: Pesquisar tecnologias compatíveis para a resolução do problema.
## Descrição do problema:

1- A falta de monitoramento causa grandes problemas nos Datacenters,  como consequência dowtimes nos servidores; e
2- A falta de alertas para o administrador para o  monitoramento da temperatura e decisão de uma ação de contenção e prevenção.

## Objetivo:
1- Criação de uma solução Open source, viável economicamente e confiável;
2- Integração de Sensores de temperatura e gás;
3- Configuração de alertas para o administrador; e
4- implementar alertas de temperatura.

## Passos para verificação:
1- Identificação da ausência de monitoramento em Datacenters; e
2- Verificação de alertas de temperaturas em sistemas atuais.

---------------------------------------------------------------------------------------------------------------------
## Resultado da pesquisa:

1. Data do Envio do Sprint 1
Data de Envio: 01/08/2024
2. Descrição do Problema
Desafios Enfrentados:
Falta de Monitoramento: Data centers sem monitoramento adequado enfrentam graves problemas, como aumentos nos downtimes dos servidores. A ausência de supervisão em tempo real pode levar a falhas não detectadas, prejudicando a operação dos servidores e serviços associados.
Falta de Alertas: Sem um sistema de alertas eficiente, os administradores não são notificados sobre condições críticas, como variações de temperatura. Isso impede ações preventivas e corretivas rápidas, elevando o risco de problemas graves e danos aos equipamentos.
3. Objetivo
O que Queremos Alcançar:
Solução Open Source: Desenvolver uma solução acessível e confiável utilizando tecnologias open source. Planejamos usar um servidor Apache com um banco de dados SQL para garantir eficiência e flexibilidade no gerenciamento dos dados.
Integração de Sensores: Implementar sensores de temperatura e gás para monitorar as condições do data center em tempo real. Esses sensores se comunicarão via IoT e os dados serão processados por um microcontrolador ESP32 em conjunto com o sensor AHT10, sendo armazenados em um banco de dados dinâmico.
Alertas para Administradores: Criar um sistema de alertas que notifique os administradores sobre qualquer anomalia detectada pelos sensores. Implementar alertas específicos para mudanças bruscas de temperatura e enviar notificações por VOIP em casos críticos, permitindo a ativação de dispositivos de contenção, se necessário.
4. Passos para Verificação
Como Vamos Verificar:
Avaliar Monitoramento Atual: Identificar as lacunas no monitoramento atual dos data centers e as áreas que precisam de melhorias.
Revisar Alertas de Temperatura: Avaliar a eficácia dos sistemas de alerta de temperatura existentes para verificar se atendem às necessidades e identificar oportunidades para aprimoramento.

---------------------------------------------------------------------------------------------------------------------

## Definições dos Sensores Utilizados:

Sensor de Temperatura e Umidade AHT10

Descrição: O AHT10 é um sensor de alta precisão para medir temperatura e umidade. É conhecido por seu baixo consumo de energia e pequenas dimensões, tornando-o ideal para aplicações em que o espaço é limitado.
Funções:
Temperatura: Mede a temperatura ambiente com precisão.
Umidade: Mede a umidade relativa do ambiente.
Aplicação: Ideal para monitorar as condições ambientais em data centers e outros locais sensíveis, fornecendo dados essenciais para manter condições ideais e evitar falhas de equipamentos.
Sensor de Fumaça MQ-2

Descrição: O MQ-2 é um sensor de gás que pode detectar a presença de fumaça, bem como gases como metano e propano. É amplamente utilizado em sistemas de detecção de fumaça e gases nocivos.
Funções:
Detecção de Fumaça: Identifica a presença de fumaça no ambiente.
Detecção de Gases: Pode detectar outros gases, proporcionando uma camada adicional de segurança.
Aplicação: Utilizado para monitorar a presença de fumaça e gases perigosos em ambientes críticos, como data centers, para acionar alarmes e dispositivos de contenção quando necessário.
Placa WEMOS D1 MINI

Descrição: A WEMOS D1 MINI é uma placa de desenvolvimento baseada no microcontrolador ESP8266, que inclui conectividade Wi-Fi. É usada para construir projetos de Internet das Coisas (IoT) devido à sua compactação e capacidades de rede.
Funções:
Conectividade Wi-Fi: Permite que a placa se conecte à rede e transmita dados sem fio.
Programação: Pode ser programada para coletar dados de sensores e controlar outros dispositivos.
Aplicação: Ideal para integrar sensores de temperatura e umidade com um sistema de monitoramento central, permitindo a coleta e transmissão de dados via Wi-Fi.
Placa ESP-01 com Módulo Relé

Descrição: A ESP-01 é um módulo baseado no ESP8266, com capacidade de conexão Wi-Fi. O módulo relé é usado para controlar dispositivos eletrônicos, permitindo que sejam ligados ou desligados remotamente.
Funções:
Controle de Dispositivos: O módulo relé pode acionar dispositivos elétricos, como sistemas de resfriamento ou alarmes.
Conectividade Wi-Fi: Permite que o módulo se comunique com o sistema de monitoramento e receba comandos.
Aplicação: Usado para ativar dispositivos de contenção com base nas notificações de alerta, ajudando a responder automaticamente a situações críticas.

**Comment by britox-x** [comment]
## Definições dos Sensores Utilizados:

Sensor de Temperatura e Umidade AHT10

Descrição: O AHT10 é um sensor de alta precisão para medir temperatura e umidade. É conhecido por seu baixo consumo de energia e pequenas dimensões, tornando-o ideal para aplicações em que o espaço é limitado.
Funções:
Temperatura: Mede a temperatura ambiente com precisão.
Umidade: Mede a umidade relativa do ambiente.
Aplicação: Ideal para monitorar as condições ambientais em data centers e outros locais sensíveis, fornecendo dados essenciais para manter condições ideais e evitar falhas de equipamentos.
Sensor de Fumaça MQ-2

Descrição: O MQ-2 é um sensor de gás que pode detectar a presença de fumaça, bem como gases como metano e propano. É amplamente utilizado em sistemas de detecção de fumaça e gases nocivos.
Funções:
Detecção de Fumaça: Identifica a presença de fumaça no ambiente.
Detecção de Gases: Pode detectar outros gases, proporcionando uma camada adicional de segurança.
Aplicação: Utilizado para monitorar a presença de fumaça e gases perigosos em ambientes críticos, como data centers, para acionar alarmes e dispositivos de contenção quando necessário.
Placa WEMOS D1 MINI

Descrição: A WEMOS D1 MINI é uma placa de desenvolvimento baseada no microcontrolador ESP8266, que inclui conectividade Wi-Fi. É usada para construir projetos de Internet das Coisas (IoT) devido à sua compactação e capacidades de rede.
Funções:
Conectividade Wi-Fi: Permite que a placa se conecte à rede e transmita dados sem fio.
Programação: Pode ser programada para coletar dados de sensores e controlar outros dispositivos.
Aplicação: Ideal para integrar sensores de temperatura e umidade com um sistema de monitoramento central, permitindo a coleta e transmissão de dados via Wi-Fi.
Placa ESP-01 com Módulo Relé

Descrição: A ESP-01 é um módulo baseado no ESP8266, com capacidade de conexão Wi-Fi. O módulo relé é usado para controlar dispositivos eletrônicos, permitindo que sejam ligados ou desligados remotamente.
Funções:
Controle de Dispositivos: O módulo relé pode acionar dispositivos elétricos, como sistemas de resfriamento ou alarmes.
Conectividade Wi-Fi: Permite que o módulo se comunique com o sistema de monitoramento e receba comandos.
Aplicação: Usado para ativar dispositivos de contenção com base nas notificações de alerta, ajudando a responder automaticamente a situações críticas.

**Comment by wesleycstr** [comment]
Obrigado Matheus! Irei acrescentar ao relatório.
