### ISSUE TITLE
Sprint 01: Levantamento de serviços e métodos necessários para coleta, envio, armazenagem, tratamento e automatização de alertas

### ISSUE THREAD

**Issue by wesleycstr** [Asset-Sentry/principal#4]
# Objetivo deste Sprint: Pesquisar os serviços compatíveis para a resolução do problema.
## Descrição do problema:

1- A falta de monitoramento causa grandes problemas nos Datacenters,  como consequência dowtimes nos servidores; e
2- A falta de alertas para o administrador para o  monitoramento da temperatura e decisão de uma ação de contenção e prevenção.

## Objetivo:
1- Criação de uma solução Open source, viável economicamente e confiável;
2- Integração de Sensores de temperatura e gás;
3- Configuração de alertas para o administrador; e
4- implementar alertas de temperatura.

## Passos para verificação:
1- Identificação da ausência de monitoramento em Datacenters; e
2- Verificação de alertas de temperaturas em sistemas atuais.

---------------------------------------------------------------------------------------------------------------------

**Comment by edmarrn** [comment]
## De acordo com as decisões e tarefas definidas tomadas na reunião segue abaixo as tarefas distribuídas:
**1-Criação de repositório para o projeto**
         Descrição: Criação de uma conta de organização na plataforma Github. Inclusão do email dos alunos e dos orientadores.
**2- Criação do arquivo readme no repositório**
        Descrição: Submissão da proposta do projeto corrigida no arquivo readme do repositório.
**3-Inclusão** do planejamento dos seis sprints como milestones
        Descrição: criação e configuração de seis marcos (milestones) no GitHub para representar as entregas do projeto.
**4-Planejamento do primeiro sprint em termos de issues**
        Descrição: criação de no mínimo um issue por membro de grupo em cada sprint/milestone.
**5-Elaboração do relatório da atividade**
        Descrição: Elaboração de relatório com os resultados obtidos no repositório do projeto, incluindo todas as 
        atividades que foram desenvolvidas por cada membro do grupo.
**6-Revisão e submissão do relatório**
        Descrição: Revisão do relatório elaborado verificando se está em conformidade com o solicitado na atividade. 
        Após revisão, submeter no classroom.

![image](https://github.com/user-attachments/assets/946f23fe-970e-4dcf-8385-ba9a60cfce9d)

**Comment by edmarrn** [comment]
No Sprint 01 na qual eu fiquei responsável do Levantamento de serviços e métodos necessários para coleta, envio, armazenagem, tratamento e automatização de alertas, em anexo segue a documentação do que eu pesquisei e também estará inserido no relatório nesta entrega.
[Planejamento dos sprints.pdf](https://github.com/user-attachments/files/16436353/Planejamento.dos.sprints.pdf)

**Comment by edmarrn** [comment]
![image](https://github.com/user-attachments/assets/939ee82e-3e2f-444a-84ef-ccdb506067f5)

**Comment by edmarrn** [comment]
De acordo com as pesquisas realizadas para o planejamento do primeiro sprint-01 e a preparação do ambiente de desenvolvimento do projeto, foi feito o seguinte levantamento:
 Serviços necessários:
Hardware:
Sensores de Temperatura;
Sensores de umidade do ar;
Sensores de gás.

Microcontroladores / Placas de desenvolvimento:				Os componentes descritos abaixo são necessários para a coleta de dados para o sistema de monitoramento de climatização Asset Sentry.

**Comment by wesleycstr** [comment]
Obrigado Edmar! Irei acrescentar ao relatório.
