### ISSUE TITLE
Sprint 02 (Edmar): Programação da plataforma de coleta e envio de dados.

### ISSUE THREAD

**Issue by wesleycstr** [Asset-Sentry/principal#6]
# Programação da plataforma de coleta e envio de dados
## Responsável: Edmar

**Comment by wesleycstr** [comment]
Edmar, o envio será através de método POST, ou seja, o seu código deverá apontar para um arquivo no servidor web e passar os parâmetros de temperatura e umidade. Exemplo: http://sensores/inserir_dados.php?temperatura=32&umidade=68 (chamei o arquivo inserir_dados.php e passei para ele as variáveis temperatura e umidade).

**Comment by wesleycstr** [comment]
Inseri o arquivo enviar_dados.php que receberá os dados da placa Wemos e irá inserir no banco de dados. Link do arquivo: https://github.com/Asset-Sentry/principal/tree/main/c%C3%B3digos/pagina_web

**Comment by edmarrn** [comment]
Acabei de inserir o código que faz a leitura dos dados coletados da temperatura e umidade do ar, usando a biblioteca **adafruit** para ler os dados, inicializa a comunicação serial, tenta iniciar o sensor AHT10,vai ler os dados de temperatura e umidade, envia os valores na porta serial e espera o tempo determinado no código para repetir o processo.

**Comment by edmarrn** [comment]
Na imagem segue o fluxograma da execução do código de leitura da temperatura e umidade do ar.
![imagem_2024-08-03_232742423](https://github.com/user-attachments/assets/46d786ce-ca6b-4ebf-8a29-8de219ca9f2e)

**Comment by wesleycstr** [comment]
Obrigado pela colaboração!
