### ISSUE TITLE
Sprint 02 (Matheus): Montagem do circuito, testes e correção de erros.

### ISSUE THREAD

**Issue by wesleycstr** [Asset-Sentry/principal#7]
# Montagem do circuito, testes e correção de erros
## Responsável: Matheus

**Comment by britox-x** [comment]
1. Simples e Direto:

"Primeiro, idealizamos tudo de forma similar em simuladores como o ThinkerCAD e o Wokwi para iniciar o processo de prototipagem física."
2. Com mais ênfase na importância dos simuladores:

"Inicialmente, utilizamos simuladores como o ThinkerCAD e o Wokwi para idealizar o projeto de maneira similar, facilitando o início do processo de prototipagem física."
3. Destacando a transição do digital para o físico:

"Começamos idealizando o projeto em simuladores como o ThinkerCAD e o Wokwi, que nos permitiram transitar para a prototipagem física de maneira eficiente."
4. Enfatizando a precisão do processo de prototipagem:

"Inicialmente, idealizamos o projeto de forma precisa em simuladores como o ThinkerCAD e o Wokwi, o que nos proporcionou uma base sólida para iniciar a prototipagem física."
5. Com foco na importância dos simuladores na prototipagem:

"Utilizamos simuladores como o ThinkerCAD e o Wokwi para idealizar o projeto de forma semelhante, garantindo um início eficiente ao processo de prototipagem física."

**Comment by britox-x** [comment]
Modelo básico:

  
![image](https://github.com/user-attachments/assets/d354ca65-74b7-4cdc-b546-6ea7cc063ad7)

**Comment by britox-x** [comment]
Modelo de testes no thinkercad:
![image](https://github.com/user-attachments/assets/fab230db-91dd-4ed5-8cea-718b93367e26)

**Comment by wesleycstr** [comment]
Muito bom Matheus! Peço que crie um arquivo .md na pasta Sprint_02 e coloque também essas informações para contar como commint. Link da pasta: https://github.com/Asset-Sentry/principal/tree/main/sprint_02

**Comment by britox-x** [comment]
Pode deixar.

**Comment by wesleycstr** [comment]
#### Olha a foto do circuito montado. Tem um erro... Consegue ver?
![image](https://github.com/user-attachments/assets/01376835-58f9-454e-b14c-346a08bcd733)

**Comment by wesleycstr** [comment]
Acabei trocando a alimentação do sensor, isso fez com que a placa nem mesmo se inicie.

**Comment by wesleycstr** [comment]
Obrigado Matheus pela colaboração!
